[package]
authors = ["Yuji Tanaka <yuji.tanaak@gmail.com>"]
name = "rusty-keys-hello"
edition = "2021"
version = "0.1.0"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
defmt = "0.3.8"
defmt-rtt = "0.4.1"
panic-probe = { version = "0.3.2", features = ["print-defmt"] }
rp-pico = "0.8.0"

[profile.release]
debug = 2